#!/usr/bin/s6-env sh

if [ -e "${STORAGE}p3" ]; then
    mkdir -p /var/lib/docker
    mountpoint -q /var/lib/docker
    if [ $? != 0 ]; then
        mount -t ext4 -o noatime,nodiratime,nodev,nobarrier "${STORAGE}p3" /var/lib/docker
    fi
fi

if [ -e "${STORAGE}p1" ]; then
    mkdir -p /boot
    mountpoint -q /boot
    if [ $? != 0 ]; then
        mount "${STORAGE}p1" /boot

        cat "${ENV_FILE}" | tr '=' ' ' \
        | while read key val; do
            echo "$val" > /etc/s6-init/env/"$key"
        done

	if [ -f /boot/config/ssh/id_rsa ] && [ -f /boot/config/ssh/id_rsa.pub ]; then
	    mkdir -p /root/.ssh
	    cp -r /boot/config/ssh/* /root/.ssh
	    chmod 0600 /root/.ssh/*
	fi
    fi
fi
