#!/bin/sh

mkdir -p /run/dropbear
touch /var/log/lastlog

if [ ! -f "/run/dropbear/host_ecdsa" ]; then
    dropbearkey -t ecdsa -f "/run/dropbear/host_ecdsa" -s 256
fi

chmod 0600 /run/dropbear/host_ecdsa

exec dropbear -r /run/dropbear/host_ecdsa -F -E -p 0.0.0.0:22
