version: '3.2'

services:

  ceph:
    image: ceph/demo:latest
    volumes:
      - /etc/ceph:/etc/ceph
      - ceph:/var/lib/ceph
      - /var/log/ceph:/var/log/ceph
    environment:
      - "CLUSTER=s3"
      - "CEPH_PUBLIC_NETWORK=0.0.0.0/0"
      - "CEPH_DEMO_UID=s3"
      - "CEPH_DEMO_ACCESS_KEY={{ access_key }}"
      - "CEPH_DEMO_SECRET_KEY={{ secret_key }}"
      - "MON_NAME=s3-mon"
      - "MON_IP=0.0.0.0"
      - "RGW_NAME=s3-gw"
    deploy:
      placement:
        constraints: [node.platform.arch == x86_64]

  agent:
    image: portainer/agent:linux-arm64
    environment:
      AGENT_CLUSTER_ADDR: tasks.monitor_agent
      AGENT_PORT: 9001
      LOG_LEVEL: info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - private
    deploy:
      mode: global
      placement:
        constraints: [node.platform.arch == aarch64]

  web:
    image: portainer/portainer
    command: -H tcp://tasks.monitor_agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - private
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.arch == x86_64]

networks:
  private:
    external: true

volumes:
  portainer:
