#!/usr/bin/s6-env sh

REXRAY_CONFIG="${REXRAY_CONFIG:-/etc/rexray/rexray.yml}"

mkdir -p /run/docker/plugins /var/cache/rexray

while [ ! -f /etc/s6-init/env/S3FS_SECRETKEY ]; do
    sleep 2
done

exec s6-env rexray start -f --nopid -c ${REXRAY_CONFIG} -s s3fs
