---
- hosts: ec2
  gather_facts: no
  roles: 
    - { role: manager }

- hosts: all
  gather_facts: no
  roles: 
    - { role: wireguard }
    - { role: swarm }

- hosts: all
  gather_facts: no
  roles: 
    - { role: storage }
