---
- name: set internal address
  set_fact:
    private_ip: "10.0.0.{{ groups['all'].index(inventory_hostname) + 1 }}"

- name: get hostname
  set_fact:
    hostname: "aws{{ groups['ec2'].index(inventory_hostname) + 1 }}"
  when: "inventory_hostname in groups['ec2']"

- name: get hostname
  set_fact:
    hostname: "zone{{ groups['local'].index(inventory_hostname) + 1 }}"
  when: "inventory_hostname in groups['local']"

- name: set hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: set hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: set hostname
  shell: hostname "{{ hostname }}"

- name: inspect swarm cluster
  docker_swarm:
    state: inspect
  register: swarm_info

- name: stop swarm cluster
  docker_swarm:
    state: absent
    force: yes
  when: "swarm_info.result != ''"

- name: start swarm cluster
  docker_swarm:
    state: present
    advertise_addr: wg0
    election_tick: 5
    heartbeat_tick: 2
  register: init_info
  when: "inventory_hostname == groups['ec2'][0]"

- name: get manager token
  set_fact:
    swarm_token: "{{ init_info.swarm_facts.JoinTokens.Manager }}"
  when: "inventory_hostname == groups['ec2'][0]"

- name: distribute manager token
  set_fact:
    swarm_token: "{{hostvars[groups['ec2'][0]]['swarm_token'] }}"
  when: "inventory_hostname != groups['ec2'][0]"

  #  delegate_to: "{{ groups['ec2'][0] }}"
  #delegate_facts: True
  #when: "inventory_hostname != groups['ec2'][0]"

- name: join swarm cluster as manager
  docker_swarm:
    state: join
    advertise_addr: wg0
    join_token: "{{ swarm_token }}"
    remote_addrs: ["{{ leader_ip }}:2377"]
  when: "inventory_hostname != groups['ec2'][0]"

#- name: create docker overlay network
#  docker_network:
#    name: internal
#    driver: overlay
#    ipam_options:
#      subnet: "{{ overlay_subnet }}"
#      gateway: "{{ overlay_subnet | ipaddr('net') | ipaddr('1') | ipaddr('ip') }}"
#      iprange: "{{ overlay_iprange }}"
#  when: "inventory_hostname != groups['ec2'][0]"
