#!/bin/sh

arch="$(uname -m)"
accesskey="AKIAIB45ZPGM7TIDEWLA"
secretkey="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"

docker run -it --rm \
	-v /etc/ansible:/etc/ansible \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-v /boot/config/ssh:/root/.ssh \
	-e AWS_ACCESS_KEY_ID=${accesskey} \
	-e AWS_SECRET_ACCESS_KEY=${secretkey} \
	homemate/ansible:latest-${arch} \
	"${@}"
