ARG ver
FROM arm64v8/alpine:${ver}

ADD rootfs/ /
ADD s6.tgz /

RUN set -x \
    && apk update \
    && apk upgrade \
    && apk-install ca-certificates curl \
    && cont-cleanup

ENTRYPOINT ["/bin/sh"]
