#!/bin/sh

echo "=> Updating docker..."
apk fix
apk add docker
rm -f /var/cache/apk/*

# wait while docker starting
docker ps > /dev/null
until [ $? != 1 ]; do 
    docker ps > /dev/null
done

# start docker services
#for name in ${srv}; do
    #echo "=> Starting docker-${name}..."
    #docker pull ${repo}/${name}:latest
    #docker inspect ${name} 1> /dev/null 2> /dev/null
    #if [ $? != 0 ]; then
    #    docker run --name=${name} --restart=always --net=host --volume /var/lib/docker/data/${name}:/data --detach ${repo}/${name}:latest
    #fi
#done
