#!/usr/bin/s6-env sh

modprobe 8189fs

ip link set wlan0 up
iwconfig wlan0 essid "${WIFI_AP}"

if [ "${WIFI_KEY}" != "" ]; then
    mkdir -p /etc/wpa_supplicant
    wpa_passphrase "${WIFI_AP}" "${WIFI_KEY}" > /etc/wpa_supplicant/wpa_supplicant.conf
    exec wpa_supplicant -Dwext -iwlan0 -c/etc/wpa_supplicant/wpa_supplicant.conf
else
    while true; do
        sleep 1d
    done
fi
