#!/usr/bin/s6-env sh

disk=/dev/mmcblk0

if [ ! -e "${disk}p2" ]; then
    start=$(($(fdisk -l "${disk}" | grep FAT32 | awk '{ print $5 }') + 1))
    cat <<EOF | fdisk -u "${disk}" 2>/dev/null 1>&2
n
p
2
${start}

w
EOF
    sync
    mkfs.ext4 "${disk}p2"
fi

mkdir -p /var/lib/docker

mountpoint /var/lib/docker > /dev/null
if [ $? != 0 ]; then
    mount -t ext4 -o noatime,nodiratime,nodev,barrier=0 "${disk}p2" /var/lib/docker
fi

if [ -e "${disk}p1" ]; then
    mkdir -p /boot
    mountpoint /boot > /dev/null
    if [ $? != 0 ]; then
        mount "${disk}p1" /boot
    fi

    cat /boot/config | tr '=' ' ' \
    | while read key val; do
        echo "$val" > /etc/s6-init/env/"$key"
    done

    cat /etc/s6-init/env/S3FS_ACCESSKEY | tr -d '\n' > /etc/passwd-s3fs
    cat /etc/s6-init/env/S3FS_SECRETKEY | awk '{ print ":" $0 }' >> /etc/passwd-s3fs
    chmod 0400 /etc/passwd-s3fs
fi
