#!/bin/sh

disk=/dev/mmcblk0

if [ ! -e "${disk}p2" ]; then
    start=$(($(fdisk -l "${disk}" | grep FAT32 | awk '{ print $5 }') + 1))
    cat <<EOF | fdisk -u "${disk}" 2>/dev/null 1>&2
n
p
2
${start}

w
EOF
    sync
    #yes | mkfs.ext4 "${disk}p2"
    mkfs.ext4 "${disk}p2"
fi

mkdir -p /var/lib/docker

mountpoint /var/lib/docker > /dev/null
if [ $? != 0 ]; then
    mount -t ext4 -o relatime,discard "${disk}p2" /var/lib/docker
fi
