#!/bin/sh

set -x

disk=/dev/mmcblk0
repo=allwinner
srv="knxd homeassistant homebridge"

if [ ! -e "${disk}p2" ]; then
    start=$(($(fdisk -l "${disk}" | grep FAT32 | awk '{ print $5 }') + 1))
    cat <<EOF | fdisk -u "${disk}" 2>/dev/null 1>&2
n
p
2
${start}

w
EOF
    sync
    yes | mkfs.ext4 "${disk}p2"
fi

mkdir -p /var/lib/docker

mountpoint /var/lib/docker > /dev/null
if [ $? != 0 ]; then
    mount -t ext4 -o relatime,discard "${disk}p2" /var/lib/docker
fi

apk fix
apk add docker
rm -f /var/cache/apk/*

# wait while docker starting
docker ps > /dev/null
until [ $? != 1 ]; do 
    docker ps > /dev/null
done

# start docker services
for name in ${srv}; do
    docker pull ${repo}/${name}:latest
    #docker inspect ${name} 1> /dev/null 2> /dev/null
    #if [ $? != 0 ]; then
    #    docker run --name=${name} --restart=always --net=host --volume /var/lib/docker/data/${name}:/data --detach ${repo}/${name}:latest
    #fi
done
