#!/bin/sh

#SWAPFILE=/var/lib/docker/.swap
SIZE=128M

echo lz4 > /sys/block/zram1/comp_algorithm
echo 4 > /sys/block/zram1/max_comp_streams
echo $SIZE > /sys/block/zram1/disksize
mkswap /dev/zram1
swapon -p 100 /dev/zram1

#if [ ! -f "${SWAPFILE}" ]; then
#    dd if=/dev/zero of="${SWAPFILE}" bs=1M count=2048
#    chmod 0600 "${SWAPFILE}"
#fi

#mkswap "${SWAPFILE}"
#swapon -p 0 "${SWAPFILE}"
