---
- name: AWS controller setup
  hosts: localhost
  gather_facts: no

  tasks:
  - include_vars: group_vars/all/ec2_vars.yml

  - name: Create security group for new instances
    ec2_group:
      region: "{{ region }}"
      name: fw-ec2
      description: fw rules for cloud controllers
      rules: "{{ sg_rules|list }}"
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0

  - name: Generate private RSA key
    command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
    args:
      creates: /root/.ssh/id_rsa

  - name: Generate public RSA key
    command: ssh-keygen -y -f /root/.ssh/id_rsa > /root/.ssh/id_rsa.pub
    args:
      creates: /root/.ssh/id_rsa.pub

  - name: Add SSH key
    ec2_key:
      region: "{{ region }}"
      name: ansible-key
      key_material: "{{ item }}"
    with_file: "{{ ssh_key }}"

  - name: Create master instances
    ec2:
      region: "{{ region }}"
      zone: "{{ zone }}"
      group: "{{ group }}"
      instance_type: "{{ machine }}"
      termination_protection: yes
      image: "{{ image }}"
      exact_count: "{{ count }}"
      count_tag:
        Type: controller
      key_name: ansible-key
      instance_tags:
        Type: controller
      monitoring: no
      wait: true
      wait_timeout: 500
      vpc_subnet_id: "{{ subnet }}" 
      assign_public_ip: yes
    register: ec2

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22
      delay: 10
      timeout: 60
      state: started
    with_items: "{{ ec2.instances }}"

  #- name: Add hosts to inventory group
  #  add_host: hostname={{ item.public_ip }} groupname=ec2
  #  with_items: "{{ ec2.instances }}"
