---
- name: install python
  raw: apk -U add python
  ignore_errors: true

- name: update apk repositories
  template:
    src: repositories.j2
    dest: /etc/apk/repositories
    owner: root
    group: root
    mode: 0644

- name: upgrade installed packages
  apk:
    update_cache: yes
    upgrade: yes

- name: install system packages
  apk:
    name: "{{ item }}"
    state: latest
  loop:
    - bash
    - docker
    - py-pip
    - linux-vanilla
    - wireguard-tools

- name: remove old kernel
  apk:
    name: "{{ item }}"
    state: absent
  loop:
    - linux-hardened

- name: enable wireguard module
  template:
    src: wireguard.j2
    dest: /etc/modules-load.d/wireguard.conf
    owner: root
    group: root
    mode: 0644

- name: check if restart needed
  shell: uname -r
  register: uname_out

- name: restart instance
  shell: 'sleep 1 && reboot && sleep 1'
  when: uname_out.stdout.find('vanilla') == -1
  async: 1
  poll: 0

- name: wait for restart
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=1
  when: uname_out.stdout.find('vanilla') == -1

- name: install ansible dependencies
  shell: pip install "{{ item }}"
  loop:
    - docker
    - jsondiff

- name: start docker
  service:
    name: docker
    enabled: yes
    state: started
